// Generated by LiveScript 1.2.0
require(!{
  path: path
});
'use strict';
module.exports = function(grunt){
  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-contrib-connect');
  return grunt.initConfig({
    jshint: {
      options: {
        node: true
      },
      all: ['Gruntfile.js', 'app/js/*.js']
    },
    connect: {
      server: {
        options: {
          port: 9000,
          keepalive: true,
          middleware: function(connect){
            var ret;
            return ret = [connect['static'](path.resolve('app')), connect['static'](path.resolve('.tmp'))];
          }
        }
      }
    }
  });
};